#!/usr/bin/env python3
"""
Generate the repo's brand lockups from the brand kit — kerning-correct.

    uv run --with fonttools --with brotli \
      python Nostos.Frontend/tools/gen-brand-lockups.py

Writes docs/brand/{logo-light,logo-dark,mark}.svg.

WHY OUTLINED WORDMARKS
  The kit's editable lockups (05_Lockups/*.svg) use <text> + font-family
  'Hanken Grotesk'. That renders fine inside the app, but GitHub (and any
  sanitiser with a strict CSP) strips webfonts, so the wordmark silently falls
  back to a default sans and the lockup breaks. Anything that leaves the app must
  therefore carry the wordmark as outlines. `brand-guidelines.md` says the same:
  convert <text> to outlines before it goes out.

WHY THE POSITIONS ARE HARD-CODED
  Computing glyph advances from fontTools ALONE ignores kerning and drifted the
  wordmark +3px from the 5th glyph (the 't'->'o' pair). The START offsets below
  were read from the browser's own text layout
  (SVGTextContentElement.getStartPositionOfChar), which applies kerning AND
  letter-spacing. They are verified pixel-identical to the kit's <text> render:
  all six glyphs land on the same pixel columns, wordmark width 693px in both.

  To re-derive (e.g. if the lockup geometry changes), render
  05_Lockups/nostos-horizontal-editable.svg with Hanken Grotesk loaded and read
  getStartPositionOfChar(i).x for i in 0..5. Do not eyeball these numbers.

VERIFY AFTER ANY CHANGE
  Render docs/brand/logo-light.svg and the kit lockup at the same viewBox and
  diff the ink masks: the bounding boxes and per-glyph columns must match.
"""
from __future__ import annotations

import os
import sys
import urllib.request

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "docs", "brand")
FONT_URL = ("https://fonts.gstatic.com/s/hankengrotesk/v12/"
            "ieVq2YZDLWuGJpnzaiwFXS9tYvBRzyFLlZg_f_NcgWZq5vBJ.ttf")
FONT_CACHE = os.path.join(os.path.expanduser("~"), ".cache", "nostos", "HankenGrotesk-500.ttf")

FOREST = "#293E32"
PAPER = "#FDF8F6"
INK = "#1C1B1A"
WORD = "nostos"

# Locked master geometry (brand-guidelines.md). Never recentre the doorway.
CANVAS = 1840, 512
MARK_SCALE = 0.5
TILE_R = 205
ARCH_D = ("M 282 764 L 282 509 A 229 234 0 0 1 740 509 L 740 764 Z "
          "M 358 764 L 358 509 A 110 112 0 0 1 578 509 L 578 764 Z")

# Horizontal lockup: baseline 345, font-size 255, letter-spacing -8.
H_BASELINE, H_SIZE = 345.0, 255.0
H_STARTS = [625.0, 758.0, 896.625, 1008.7344, 1088.2031, 1226.8281]


def font_path() -> str:
    if not os.path.exists(FONT_CACHE):
        os.makedirs(os.path.dirname(FONT_CACHE), exist_ok=True)
        print(f"fetching Hanken Grotesk 500 -> {FONT_CACHE}")
        with urllib.request.urlopen(FONT_URL) as r, open(FONT_CACHE, "wb") as f:
            f.write(r.read())
    return FONT_CACHE


def glyph_paths(starts, size, baseline, font_file):
    font = TTFont(font_file)
    upem = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    scale = size / upem
    out = []
    for ch, x in zip(WORD, starts):
        if ord(ch) not in cmap:
            raise SystemExit(f"Hanken Grotesk has no glyph for {ch!r}")
        pen = SVGPathPen(gs)
        gs[cmap[ord(ch)]].draw(pen)
        d = pen.getCommands()
        if d:
            out.append(f'<path transform="translate({x:.4f} {baseline:.4f}) '
                       f'scale({scale:.8f} {-scale:.8f})" d="{d}"/>')
    return out


def lockup(word_fill, font_file):
    glyphs = "\n    ".join(glyph_paths(H_STARTS, H_SIZE, H_BASELINE, font_file))
    w, h = CANVAS
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-label="Nostos">
  <title>Nostos</title>
  <!-- GENERATED by Nostos.Frontend/tools/gen-brand-lockups.py — do not hand-edit.
       Wordmark is OUTLINED (no <text>/webfont) so it survives sanitisers that strip
       fonts (GitHub, strict-CSP renderers); those would otherwise silently fall back
       to a default sans and break the lockup.
       Mark: Forest tile + Paper arch (the theme-invariant primary variant). -->
  <g transform="scale({MARK_SCALE})">
    <rect x="0" y="0" width="1024" height="1024" rx="{TILE_R}" fill="{FOREST}"/>
    <path d="{ARCH_D}" fill="{PAPER}" fill-rule="evenodd"/>
  </g>
  <g fill="{word_fill}">
    {glyphs}
  </g>
</svg>
"""


def mark_only():
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img" aria-label="Nostos brand mark">
  <title>Nostos mark</title>
  <rect x="0" y="0" width="1024" height="1024" rx="{TILE_R}" fill="{FOREST}"/>
  <path d="{ARCH_D}" fill="{PAPER}" fill-rule="evenodd"/>
</svg>
"""


def main() -> int:
    f = font_path()
    os.makedirs(OUT, exist_ok=True)
    # logo-light is for LIGHT surfaces (Ink wordmark); logo-dark for DARK
    # surfaces (Paper wordmark). The mark itself is identical in both.
    files = {
        "logo-light.svg": lockup(INK, f),
        "logo-dark.svg": lockup(PAPER, f),
        "mark.svg": mark_only(),
    }
    for name, content in files.items():
        path = os.path.join(OUT, name)
        with open(path, "w") as fh:
            fh.write(content)
        print(f"wrote {path} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
