@host = http://localhost:5214

############################################################
# BOOKS
############################################################

### List all books
GET {{host}}/api/books
Accept: application/json


### Create a new book
POST {{host}}/api/books
Content-Type: application/json

{
  "title": "Test Book",
  "author": "Someone"
}


### Get a book by ID
# Replace BOOK_ID below after creating a book
GET {{host}}/api/books/BOOK_ID
Accept: application/json


### Update book metadata
PUT {{host}}/api/books/BOOK_ID
Content-Type: application/json

{
  "title": "Updated Title",
  "author": "Updated Author"
}


### Delete a book
DELETE {{host}}/api/books/BOOK_ID
Accept: application/json


############################################################
# NOTES
############################################################

### List notes for a book
# Replace BOOK_ID below
GET {{host}}/api/books/c6ca4603-7b6c-4534-9d2d-ec661715f497/notes
Accept: application/json


### Create a note for a book
POST {{host}}/api/books/c6ca4603-7b6c-4534-9d2d-ec661715f497/notes
Content-Type: application/json

{
  "content": "This is my first note on the book."
}


### Update a note
# Replace NOTE_ID below after creating a note
PUT {{host}}/api/notes/353cfba3-8d94-46be-aaf3-47d4de8b9453
Content-Type: application/json

{
  "content": "Updated note content."
}


### Delete a note
DELETE {{host}}/api/notes/353cfba3-8d94-46be-aaf3-47d4de8b9453
Accept: application/json


############################################################
# COLLECTIONS
############################################################

### List all collections
GET {{host}}/api/collections
Accept: application/json

### Create a new collection
POST {{host}}/api/collections
Content-Type: application/json

{
  "name": "Work"
}

### Get a collection by ID
GET {{host}}/api/collections/COLLECTION_ID
Accept: application/json

### Update a collection
PUT {{host}}/api/collections/COLLECTION_ID
Content-Type: application/json

{
  "name": "Updated Collection Name"
}

### Delete a collection
DELETE {{host}}/api/collections/COLLECTION_ID
Accept: application/json



############################################################
# CONCEPTS
############################################################

### List all concepts
GET {{host}}/api/concepts
Accept: application/json

### Create a new concept
POST {{host}}/api/concepts
Content-Type: application/json

{
  "concept": "Virtue ethics"
}

### Get a concept by ID
GET {{host}}/api/concepts/CONCEPT_ID
Accept: application/json

### Update a concept
PUT {{host}}/api/concepts/CONCEPT_ID
Content-Type: application/json

{
  "concept": "Revised concept text"
}

### Delete a concept
DELETE {{host}}/api/concepts/CONCEPT_ID
Accept: application/json
