// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nostos.Backend.Data;

#nullable disable

namespace Nostos.Backend.Migrations
{
    [DbContext(typeof(NostosDbContext))]
    [Migration("20251207193251_AddSeveralFeaturesForLibrary4")]
    partial class AddSeveralFeaturesForLibrary4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLocation")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Books");

                    b.HasDiscriminator<string>("BookType").HasValue("BookModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.ConceptModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteConceptModel", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId", "ConceptId");

                    b.HasIndex("ConceptId");

                    b.ToTable("NoteConcepts");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CfiRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Writings");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.AudioBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("audiobook");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.EBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ebook");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.PhysicalBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.ToTable("Books", t =>
                        {
                            t.Property("Isbn")
                                .HasColumnName("PhysicalBookModel_Isbn");

                            t.Property("PageCount")
                                .HasColumnName("PhysicalBookModel_PageCount");
                        });

                    b.HasDiscriminator().HasValue("physical");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.CollectionModel", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.CollectionModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteConceptModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.ConceptModel", "Concept")
                        .WithMany("NoteConcepts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nostos.Backend.Data.Models.NoteModel", "Note")
                        .WithMany("NoteConcepts")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.BookModel", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.WritingModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.ConceptModel", b =>
                {
                    b.Navigation("NoteConcepts");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.Navigation("NoteConcepts");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
