// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nostos.Backend.Cloud.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nostos.Backend.Cloud.Migrations.Postgres
{
    [DbContext(typeof(PostgresNostosDbContext))]
    [Migration("20260922170207_EstablishCloudMigrationLifecycle")]
    partial class EstablishCloudMigrationLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nostos.Backend.Data.Models.AiProviderSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LlmApiKeyEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("LlmBaseUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("LlmEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LlmModel")
                        .HasColumnType("text");

                    b.Property<string>("SttApiKeyEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("SttBaseUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("SttEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SttModel")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AiProviderSettings", t =>
                        {
                            t.HasCheckConstraint("CK_AiProviderSettings_SingletonId", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.AssistantSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaptureProcessingMode")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AssistantSettings", t =>
                        {
                            t.HasCheckConstraint("CK_AssistantSettings_SingletonId", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BackupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IncludeBookFiles")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalArchivePath")
                        .HasColumnType("text");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BackupRecords");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookAcquisitionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssetFormat")
                        .HasColumnType("text");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImportedExtension")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RightsStatement")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("ProviderId", "ExternalId", "AssetId")
                        .IsUnique();

                    b.ToTable("BookAcquisitions");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookCollectionModel", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("BookCollections");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("BookType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedAsin")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedIsbn")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("NormalizedAsin")
                        .IsUnique()
                        .HasFilter("\"NormalizedAsin\" IS NOT NULL");

                    b.HasIndex("NormalizedIsbn")
                        .IsUnique()
                        .HasFilter("\"NormalizedIsbn\" IS NOT NULL");

                    b.HasIndex("Title");

                    b.HasIndex("WorkId");

                    b.ToTable("Books");

                    b.HasDiscriminator<string>("BookType").HasValue("BookModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.ConceptModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Concept")
                        .IsUnique();

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.LibraryCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("character varying(131072)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ClientId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("LibraryCommandReceipts", t =>
                        {
                            t.HasCheckConstraint("CK_LibraryCommandReceipts_Bounds", "length(\"ClientId\") <= 64 AND length(\"IdempotencyKey\") <= 128 AND length(\"CommandKind\") <= 32 AND length(\"ResponseJson\") <= 131072");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.LibraryState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("SingletonSlot")
                        .HasColumnType("integer");

                    b.Property<string>("StateVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SingletonSlot")
                        .IsUnique();

                    b.ToTable("LibraryStates", t =>
                        {
                            t.HasCheckConstraint("CK_LibraryStates_SingletonSlot", "\"SingletonSlot\" = 1");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("character varying(131072)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ClientId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("NoteCommandReceipts", t =>
                        {
                            t.HasCheckConstraint("CK_NoteCommandReceipts_Bounds", "length(\"ClientId\") <= 64 AND length(\"IdempotencyKey\") <= 128 AND length(\"Command\") <= 32 AND length(\"ResultJson\") <= 131072");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteConceptModel", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.HasKey("NoteId", "ConceptId");

                    b.HasIndex("ConceptId");

                    b.ToTable("NoteConcepts");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnchorVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaptureSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("text");

                    b.Property<string>("CfiRange")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("verbatim");

                    b.Property<string>("RawContent")
                        .HasColumnType("text");

                    b.Property<string>("SelectedText")
                        .HasColumnType("text");

                    b.Property<string>("SourceAnchorKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unknown");

                    b.Property<string>("SourceAnchorValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WorkModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedAuthor")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAuthor");

                    b.HasIndex("NormalizedTitle");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Writings");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.AudioBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Asin")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Narrator")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("audiobook");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.EBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Isbn")
                        .HasColumnType("text");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("ebook");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.PhysicalBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Isbn")
                        .HasColumnType("text");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.ToTable("Books", t =>
                        {
                            t.Property("Isbn")
                                .HasColumnName("PhysicalBookModel_Isbn");

                            t.Property("PageCount")
                                .HasColumnName("PhysicalBookModel_PageCount");
                        });

                    b.HasDiscriminator().HasValue("physical");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookAcquisitionModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.BookModel", "Book")
                        .WithOne("Acquisition")
                        .HasForeignKey("Nostos.Backend.Data.Models.BookAcquisitionModel", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookCollectionModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.BookModel", "Book")
                        .WithMany("BookCollections")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nostos.Backend.Data.Models.CollectionModel", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.WorkModel", "Work")
                        .WithMany("Books")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nostos.Backend.Data.Models.BookMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("BookModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Categories")
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Edition")
                                .HasColumnType("text");

                            b1.Property<string>("Editor")
                                .HasColumnType("text");

                            b1.Property<string>("Language")
                                .HasColumnType("text");

                            b1.Property<string>("PlaceOfPublication")
                                .HasColumnType("text");

                            b1.Property<string>("PublishedDate")
                                .HasColumnType("text");

                            b1.Property<string>("Publisher")
                                .HasColumnType("text");

                            b1.Property<string>("Series")
                                .HasColumnType("text");

                            b1.Property<string>("Subtitle")
                                .HasColumnType("text");

                            b1.Property<string>("Translator")
                                .HasColumnType("text");

                            b1.Property<string>("VolumeNumber")
                                .HasColumnType("text");

                            b1.HasKey("BookModelId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");
                        });

                    b.OwnsOne("Nostos.Backend.Data.Models.FileInfoDetails", "FileDetails", b1 =>
                        {
                            b1.Property<Guid>("BookModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ChaptersJson")
                                .HasColumnType("text");

                            b1.Property<string>("CoverFileName")
                                .HasColumnType("text");

                            b1.Property<string>("FileName")
                                .HasColumnType("text");

                            b1.Property<bool>("HasFile")
                                .HasColumnType("boolean");

                            b1.Property<string>("LocationsJson")
                                .HasColumnType("text");

                            b1.HasKey("BookModelId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");
                        });

                    b.OwnsOne("Nostos.Backend.Data.Models.ReadingProgress", "Progress", b1 =>
                        {
                            b1.Property<Guid>("BookModelId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("FinishedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsFavorite")
                                .HasColumnType("boolean");

                            b1.Property<string>("LastLocation")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("LastReadAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("PersonalReview")
                                .HasColumnType("text");

                            b1.Property<int>("ProgressPercent")
                                .HasColumnType("integer");

                            b1.Property<int>("Rating")
                                .HasColumnType("integer");

                            b1.HasKey("BookModelId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");
                        });

                    b.Navigation("FileDetails")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Progress")
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.CollectionModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteConceptModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.ConceptModel", "Concept")
                        .WithMany("NoteConcepts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nostos.Backend.Data.Models.NoteModel", "Note")
                        .WithMany("NoteConcepts")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.BookModel", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.WritingModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookModel", b =>
                {
                    b.Navigation("Acquisition");

                    b.Navigation("BookCollections");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.ConceptModel", b =>
                {
                    b.Navigation("NoteConcepts");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.Navigation("NoteConcepts");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WorkModel", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
