import { Component, OnDestroy, OnInit, computed, inject } from '@angular/core';
import { LucideAngularModule, BookOpenCheck, RefreshCw } from 'lucide-angular';
import { Observable } from 'rxjs';

import { ReadingMode, ReadingSessionStatus } from '../core/dtos/reading-training.dtos';
import { ReadingTrainingStore } from './reading-training.store';
import { CapacityLaneView, CapacityLanesComponent } from './components/capacity-lanes/capacity-lanes.component';
import { TodaySessionComponent } from './components/today-session/today-session.component';

/** Mode presentation facts; Recovery is volume-only by policy. */
const MODE_LANES: ReadonlyArray<{ mode: ReadingMode; title: string; volumeOnly: boolean }> = [
  { mode: ReadingMode.Endurance, title: 'Endurance', volumeOnly: false },
  { mode: ReadingMode.Deep, title: 'Deep', volumeOnly: false },
  { mode: ReadingMode.Recovery, title: 'Recovery', volumeOnly: true },
];

/**
 * Reading Training page shell.
 *
 * Orchestration only: it connects the store for the route lifetime, renders
 * the store's signals (loading / error / not-initialized / initialized), and
 * forwards child-component events as typed store commands. The page owns
 * idempotency: a stable client id per page instance and a fresh idempotency
 * key generated once per user action. Mutations are never retried
 * automatically.
 */
@Component({
  standalone: true,
  selector: 'app-reading-training',
  imports: [LucideAngularModule, CapacityLanesComponent, TodaySessionComponent],
  templateUrl: './reading-training.component.html',
  styleUrl: './reading-training.component.css',
})
export class ReadingTrainingComponent implements OnInit, OnDestroy {
  readonly store = inject(ReadingTrainingStore);

  /** Stable UI client id for this page instance (never generated by store/service). */
  private readonly clientId = crypto.randomUUID();

  RefreshIcon = RefreshCw;
  SetupIcon = BookOpenCheck;

  /** Programme absent because the server reported `not_initialized`. */
  readonly notInitialized = computed(
    () =>
      !this.store.loading() &&
      this.store.dashboard() === null &&
      (this.store.error()?.includes('not_initialized') ?? false)
  );

  /** Open session projected from the authoritative dashboard snapshot. */
  readonly openSession = computed(
    () => this.store.openSession() ?? this.store.dashboard()?.openSession ?? null
  );

  /** Three capacity lanes projected from the authoritative snapshot. */
  readonly lanes = computed<CapacityLaneView[]>(() => {
    const programme = this.store.programme() ?? this.store.dashboard()?.programme ?? null;
    if (!programme) return [];
    const targets = programme.targets;
    return MODE_LANES.map((lane) => {
      const targetMinutes =
        lane.mode === ReadingMode.Endurance
          ? targets.enduranceTargetMinutes
          : lane.mode === ReadingMode.Deep
            ? targets.deepTargetMinutes
            : targets.recoveryTargetMinutes;
      const establishedMinutes =
        lane.mode === ReadingMode.Endurance
          ? targets.enduranceEstablishedMinutes
          : lane.mode === ReadingMode.Deep
            ? targets.deepEstablishedMinutes
            : targets.recoveryEstablishedMinutes;
      const book = this.store.defaultBookForMode(lane.mode);
      return {
        mode: lane.mode,
        title: lane.title,
        targetMinutes,
        establishedMinutes,
        bookTitle: book?.bookTitle ?? null,
        volumeOnly: lane.volumeOnly,
        // The dashboard snapshot does not yet carry committed review
        // decisions; the latest adaptation reason will be supplied by the
        // weekly-review slice once that data is available.
        reason: null,
      };
    });
  });

  ngOnInit(): void {
    this.store.connect();
  }

  ngOnDestroy(): void {
    this.store.disconnect();
  }

  onRefresh(): void {
    this.store.refresh();
  }

  onSetup(): void {
    this.runAction((key) => this.store.initialize({ clientId: this.clientId, idempotencyKey: key }));
  }

  onStart(): void {
    const session = this.openSession();
    if (session?.status === ReadingSessionStatus.Planned) {
      this.runAction((key) =>
        this.store.startSession({ clientId: this.clientId, idempotencyKey: key, sessionId: session.id })
      );
    } else {
      this.runAction((key) => this.store.startNewSession({ clientId: this.clientId, idempotencyKey: key }));
    }
  }

  onPause(): void {
    this.runAction((key) => this.store.pauseSession({ clientId: this.clientId, idempotencyKey: key }));
  }

  onResume(): void {
    this.runAction((key) => this.store.resumeSession({ clientId: this.clientId, idempotencyKey: key }));
  }

  onComplete(reportedMinutes?: number): void {
    this.runAction((key) =>
      this.store.completeSession({ clientId: this.clientId, idempotencyKey: key, reportedMinutes })
    );
  }

  onCancel(): void {
    this.runAction((key) => this.store.cancelSession({ clientId: this.clientId, idempotencyKey: key }));
  }

  /**
   * Dispatches one user action with a fresh idempotency key, generated here —
   * once per action — never by the store or service. Command failures are
   * surfaced by the store's error/lastReply signals; nothing is retried.
   */
  private runAction(invoke: (idempotencyKey: string) => Observable<unknown>): void {
    invoke(crypto.randomUUID()).subscribe({ error: () => void 0 });
  }
}
