import { Component, inject, OnInit, signal, model, computed, ViewChild, ElementRef, DestroyRef } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Observable, finalize } from 'rxjs';

// Store
import { BookDetailStore } from './book-detail.store';

// Reading Training (authoritative backend snapshots only)
import { ReadingTrainingStore } from '../reading-training/reading-training.store';
import {
  ReadingAssignmentStatus,
  ReadingBookAssignment,
  ReadingMode,
  ReadingSession,
  ReadingSessionStatus,
} from '../core/dtos/reading-training.dtos';

// DTOs
import { Book } from '../core/dtos/book.dtos';

// UI Components
import { AddBookModal } from '../add-book-modal/add-book-modal.component';
import { ConceptInputComponent } from '../ui/concept-input.component/concept-input.component';
import { NoteCardComponent } from '../ui/note-card.component/note-card.component';
import { StarRatingComponent } from '../ui/star-rating/star-rating.component';

// Icons
import {
  LucideAngularModule,
  ArrowLeft,
  User,
  Calendar,
  Trash2,
  Edit2,
  CircleAlert,
  BookOpen,
  CheckIcon,
  ChevronDown,
  ChevronUp,
  Hash,
  Layers,
  Building,
  BookDown,
  Image,
  Headphones,
  Clock,
  Heart,
  CheckCircle,
  Mic,
  MapPin,
  MessageSquareQuote,
} from 'lucide-angular';

@Component({
  standalone: true,
  selector: 'app-book-detail',
  imports: [
    CommonModule,
    FormsModule,
    RouterLink,
    LucideAngularModule,
    AddBookModal,
    ConceptInputComponent,
    NoteCardComponent,
    StarRatingComponent,
  ],
  providers: [BookDetailStore],
  templateUrl: './book-detail.component.html',
  styleUrls: ['./book-detail.component.css'],
})
export class BookDetail implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);

  // Inject the Store
  readonly store = inject(BookDetailStore);

  // Reading Training: the root store is the single owner of authoritative
  // snapshots (dashboard + history); this section only projects and commands.
  readonly readingTraining = inject(ReadingTrainingStore);
  private readonly destroyRef = inject(DestroyRef);

  // Icons
  ArrowLeftIcon = ArrowLeft;
  UserIcon = User;
  CalendarIcon = Calendar;
  Trash2Icon = Trash2;
  Edit2Icon = Edit2;
  AlertCircleIcon = CircleAlert;
  BookOpenIcon = BookOpen;
  CheckIcon = CheckIcon;
  ChevronDownIcon = ChevronDown;
  ChevronUpIcon = ChevronUp;
  HashIcon = Hash;
  LayersIcon = Layers;
  BuildingIcon = Building;
  BookDownIcon = BookDown;
  ImageIcon = Image;
  HeadphonesIcon = Headphones;
  ClockIcon = Clock;
  HeartIcon = Heart;
  CheckCircleIcon = CheckCircle;
  MicIcon = Mic;
  MapPinIcon = MapPin;
  QuoteIcon = MessageSquareQuote;

  // Local UI State
  isDescriptionExpanded = signal(false);
  showMetadataModal = signal(false);
  newNote = model<string>('');

  // --- Reading Training section (compact, server-authoritative) ---

  /** Modes the plan exposes on the book detail page; Recovery is volume-only. */
  readonly trainingModes: ReadingMode[] = [ReadingMode.Endurance, ReadingMode.Deep];
  readonly readingModeEnum = ReadingMode;
  readonly assignmentStatusEnum = ReadingAssignmentStatus;

  /** Stable UI client id for this page instance (never generated by store/service). */
  private readonly trainingClientId = crypto.randomUUID();

  /** True while the section's history fetch is in flight (dashboard loading is `trainingLoading`). */
  private readonly trainingHistoryLoadingState = signal(false);
  /** Last successful command reply from this section; rendered in a polite live region. */
  private readonly trainingStatusState = signal<string | null>(null);
  /** Monotonic history fetch sequence: stale responses are dropped. */
  private trainingHistorySeq = 0;

  readonly trainingHistoryLoading = this.trainingHistoryLoadingState.asReadonly();
  readonly trainingStatus = this.trainingStatusState.asReadonly();
  readonly trainingDashboard = this.readingTraining.dashboard;
  readonly trainingError = this.readingTraining.error;
  readonly trainingBusy = this.readingTraining.mutating;

  /** Programme absent because the server reported `not_initialized`. */
  readonly trainingNotInitialized = computed(
    () => this.trainingDashboard() === null && (this.trainingError()?.includes('not_initialized') ?? false)
  );

  /** Assignments of this library book (all statuses), in dashboard order. */
  readonly trainingAssignments = computed<ReadingBookAssignment[]>(() => {
    const bookId = this.store.book()?.id;
    if (!bookId) return [];
    return this.readingTraining.books().filter((assignment) => assignment.bookId === bookId);
  });

  /** This book's sessions in server (newest-first) order, capped at five. */
  readonly recentSessions = computed<ReadingSession[]>(() => {
    const bookId = this.store.book()?.id;
    if (!bookId) return [];
    return this.readingTraining.history().filter((session) => session.bookId === bookId).slice(0, 5);
  });

  // Template Refs for hidden file inputs
  @ViewChild('coverInput') coverInput!: ElementRef<HTMLInputElement>;
  @ViewChild('fileInput') fileInput!: ElementRef<HTMLInputElement>;

  ngOnInit(): void {
    this.route.paramMap.subscribe((params) => {
      const id = params.get('id');
      if (id) {
        this.store.loadAllData(id);
        this.loadTrainingData();
      }
    });
  }

  // --- UI Actions (Delegating to Store) ---

  toggleFavorite() {
    this.store.toggleFavorite();
  }
  toggleFinished() {
    this.store.toggleFinished();
  }
  onRate(rating: number) {
    this.store.rate(rating);
  }

  addNote(): void {
    const content = this.newNote().trim();
    if (!content) return;
    this.store.addNote(content);
    this.newNote.set('');
  }

  onUpdateNote(event: { id: string; content: string; selectedText?: string }): void {
    this.store.updateNote(event.id, event.content, event.selectedText);
  }

  onDeleteNote(id: string): void {
    this.store.deleteNote(id);
  }

  onConceptClick(conceptId: string): void {
    this.goToConcept(conceptId);
  }

  // --- File Actions ---

  onCoverSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) this.store.uploadCover(file);
  }

  deleteCover() {
    this.store.deleteCover();
  }

  onFileUploadSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) this.store.uploadFile(file);
  }

  // --- Navigation & Helpers ---

  goToConcept(conceptId: string): void {
    this.router.navigate(['/second-brain'], { queryParams: { conceptId } });
  }

  toggleDescription() {
    this.isDescriptionExpanded.update((v) => !v);
  }
  openMetadataModal() {
    if (this.store.book()) this.showMetadataModal.set(true);
  }
  closeMetadataModal() {
    this.showMetadataModal.set(false);
  }

  onBookUpdated(updatedBook: Book): void {
    this.store.book.set(updatedBook);
  }

  downloadFile() {
    const id = this.store.book()?.id;
    if (id) window.open(`/api/books/${id}/file`, '_blank');
  }

  openReader() {
    const id = this.store.book()?.id;
    if (id) this.router.navigate(['/read', id]);
  }

  triggerCoverPicker() {
    this.coverInput?.nativeElement.click();
  }

  triggerFilePicker() {
    this.fileInput?.nativeElement.click();
  }

  getCollectionName(id: string | null | undefined): string {
    if (!id) return '—';
    const col = this.store.collections().find((c) => c.id === id);
    return col ? col.name : '—';
  }

  isAudioBook(book: Book | null): boolean {
    return book?.type === 'audiobook';
  }

  // --- Reading Training section actions ---

  /** The assignment of this book for one mode, or null when not assigned. */
  trainingAssignmentFor(mode: ReadingMode): ReadingBookAssignment | null {
    return this.trainingAssignments().find((assignment) => assignment.mode === mode) ?? null;
  }

  trainingModeLabel(mode: ReadingMode): string {
    return mode === ReadingMode.Deep ? 'Deep' : 'Endurance';
  }

  /** Adds this library book to a training mode; the server owns the queue. */
  assignToTraining(mode: ReadingMode): void {
    const bookId = this.store.book()?.id;
    if (!bookId) return;
    this.runTrainingCommand(
      (key) =>
        this.readingTraining.addBook({
          clientId: this.trainingClientId,
          idempotencyKey: key,
          bookId,
          mode,
          makeDefault: false,
        }),
      () => this.reloadTrainingHistory()
    );
  }

  /** Makes an active assignment the default for its mode. */
  makeTrainingDefault(assignment: ReadingBookAssignment): void {
    this.runTrainingCommand((key) =>
      this.readingTraining.setDefaultBook({
        clientId: this.trainingClientId,
        idempotencyKey: key,
        bookAssignmentId: assignment.id,
        mode: assignment.mode,
      })
    );
  }

  retryTraining(): void {
    this.loadTrainingData();
  }

  // --- Reading Training section presentation helpers ---

  /** Newest-first sort key is the server's order; only the date is formatted here. */
  trainingSessionDate(session: ReadingSession): string {
    const iso = session.completedAt ?? session.plannedAt;
    const date = new Date(iso);
    if (Number.isNaN(date.getTime())) return '';
    return date.toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' });
  }

  /** Actual minutes: reported override when present, else measured seconds. */
  trainingSessionMinutes(session: ReadingSession): number {
    if (session.reportedMinutes !== null) return session.reportedMinutes;
    return Math.round(session.measuredSeconds / 60);
  }

  trainingSessionStatusLabel(status: ReadingSessionStatus): string | null {
    switch (status) {
      case ReadingSessionStatus.Completed:
        return 'Completed';
      case ReadingSessionStatus.Cancelled:
        return 'Cancelled';
      case ReadingSessionStatus.AwaitingFeedback:
        return 'Awaiting feedback';
      default:
        return null;
    }
  }

  // --- Reading Training section internals ---

  /** Fetches the authoritative dashboard + this book's sessions for this route. */
  private loadTrainingData(): void {
    this.readingTraining.refresh();
    this.reloadTrainingHistory();
  }

  /** Reloads the server session history (cold; failures keep the last good list). */
  private reloadTrainingHistory(): void {
    const seq = ++this.trainingHistorySeq;
    this.trainingHistoryLoadingState.set(true);
    this.readingTraining
      .loadHistory()
      .pipe(
        takeUntilDestroyed(this.destroyRef),
        finalize(() => {
          if (seq === this.trainingHistorySeq) this.trainingHistoryLoadingState.set(false);
        })
      )
      .subscribe({ error: () => void 0 });
  }

  /**
   * Dispatches one section command with a fresh idempotency key, generated
   * here — once per action — never by the store or service. The store runs
   * the command, refreshes the authoritative dashboard, and only then emits
   * the result; failures surface through `trainingError` and nothing is
   * retried. The reply is announced in the section's polite live region.
   */
  private runTrainingCommand(
    invoke: (idempotencyKey: string) => Observable<{ reply: string }>,
    onSuccess?: () => void
  ): void {
    this.trainingStatusState.set(null);
    invoke(crypto.randomUUID())
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (result) => {
          this.trainingStatusState.set(result.reply);
          onSuccess?.();
        },
        error: () => void 0,
      });
  }
}
